name: Feature actions
on:
  push:
    branches-ignore:
      - main
      - dev
      - 'release/**'
jobs:
  Check-News-Fragment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: newsfragments
      - uses: tj-actions/verify-changed-files@v17
        id: verify-changed-files
        with:
          files: newsfragments/*
      - if: steps.verify-changed-files.outputs.files_changed == 'false'
        run: exit 1
