name: PHP Code Checks
on:
    pull_request:
        types: [opened, synchronize, ready_for_review]
        branches: [main, dev]
        paths: '**/*.php'

jobs:
    Laravel_Pint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              run: apt-get -y install php libapache2-mod-php php-cli

            - name: Install Composer
              run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

            - name: Install Dependencies
              run: composer install

            - name: Laravel Pint
              run: ./vendor/bin/pint
